services:
  postgres:
    image: postgres:16
    container_name: kitchen_ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: kitchen_ecommerce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
